INSERT INTO properties(property_status,
                       owner_id,
                       address,
                       description,
                       rating,
                       is_long_term_rent,
                       cost,
                       area,
                       bedrooms,
                       sleeping_places,
                       bathrooms,
                       max_guests)
VALUES ('ON_MODERATION',
        1,
        'г. Воронеж, ул. Новосибирская, д. 68, кв. 228',
        'Уютная квартира с видом на 97ую школу. Рядом есть пятерочка, почта России, киоски',
        4.84,
        false,
        2400,
        43,
        2,
        4,
        1,
        4);