CREATE TABLE facilities
(
    facility_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    image_id    BIGINT UNIQUE,
    FOREIGN KEY (image_id) REFERENCES images (image_id) ON DELETE SET NULL
);