CREATE TABLE images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(400) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    additional_path VARCHAR(255) NOT NULL,
    size BIGINT NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    is_preview_image BOOLEAN
);