CREATE TABLE reservations
(
    reservation_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id       BIGINT       NOT NULL,
    renter_id         BIGINT       NOT NULL,
    start_date        DATE         NOT NULL,
    end_date          DATE         NOT NULL,
    is_long_term_rent BOOLEAN      NOT NULL,
    cost_in_period    INT          NOT NULL,
    renter_commission INT          NOT NULL,
    owner_commission  INT          NOT NULL,
    total_cost        INT          NOT NULL,
    payment_status    VARCHAR(255) NOT NULL default 'NOT_PAID',

    foreign key (property_id) references properties (property_id),
    foreign key (renter_id) references users (user_id)
);