CREATE TABLE users
(
    user_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id          BIGINT,
    name              VARCHAR(255) NOT NULL,
    surname           VARCHAR(255) NOT NULL,
    gender            VARCHAR(255),
    birth_date        DATE,
    registration_date DATE,
    email             VARCHAR(255) NOT NULL,
    FOREIGN KEY (image_id) REFERENCES images (image_id) ON DELETE SET NULL
);