CREATE TABLE properties
(
    property_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_status   VARCHAR(255) NOT NULL DEFAULT 'REJECTED',
    owner_id          BIGINT       NOT NULL,
    title             VARCHAR(255) NOT NULL,
    address           VARCHAR(255) NOT NULL,
    description       VARCHAR(2000),
    is_long_term_rent BOOLEAN      NOT NULL,
    cost              INTEGER      NOT NULL,
    area              FLOAT,
    rooms             INTEGER,
    bedrooms          INTEGER,
    sleeping_places   INTEGER,
    bathrooms         INTEGER,
    max_guests        INTEGER
);