spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 120MB
  application:
    name: rentplace
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl:
            enable: false
            #trust: smtp.gmail.com
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
logging:
  level:
    org.springframework.mail: DEBUG
    com.sun.mail: DEBUG
commission:
  for-renter:
    in-percent: 4
  for-owner:
    in-percent: 4
jwt:
  expiration-time-in-minutes:
    access: 15
  expiration-time-in-days:
    refresh: 30
  secret:
    access: IJKTakIvc2HS2/MDqMWjfFMobX13mzQWlIi5rr2fTGNNlbWkDyuGi+FJO0b82kiERAF1k05iFdymIwxtRb4vcA==
    refresh: +fTEQwJivdxcqp/FIAi6N26GWs31utu+AJ/TU6i4zINYCTCVJnIunKzOmXNCMcZgCZ74Pqi0DUBQ4vf8O5V+HA==
openrouter:
  api:
    url: ${OPENROUTER_API_URL}
    key: ${OPENROUTER_API_KEY}
    model: ${OPENROUTER_API_MODEL}
    default-system-prompt: ${OPENROUTER_API_SYSTEM_PROMPT}

api:
  path: api/v1
upload:
  path: C:/Users/Kattsyn/TP-PROJECT/Backend/rentplace/uploads
storage:
  location: ./uploads/
app:
  base-url: http://localhost:8080