spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    name: rentplace
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
api:
  path: api/v1
upload:
  path: C:/Users/Kattsyn/TP-PROJECT/Backend/rentplace/uploads
storage:
  location: ./uploads/
app:
  base-url: http://localhost:8080