spring:
  application:
    name: rentplace
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
api:
  path: api/v1
upload:
  path: ./uploads
storage:
  location: ./uploads/