name: Backend CI/CD

on:
  push:
    branches:
      - main
      - development
      - feature/**
      - bugfix/**
      - release/**
    paths:
      - 'rentplace/**'
  pull_request:
    branches:
      - main
      - development
      - feature/**
      - bugfix/**
      - release/**
    paths:
      - 'rentplace/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build
        working-directory: rentplace
        run: ./gradlew build --no-daemon

      - name: Test
        working-directory: rentplace
        run: ./gradlew test
